language: cpp
script:
    - automake --version
    - automake-1.11 --version
    - sudo add-apt-repository -y ppa:rbose-debianizer/automake &> /dev/null
    - sudo apt-get -qq update
    - sudo apt-get -qq install automake
    - automake-1.12 --version
    - automake --version
